
module.exports = function MotorcycleConstructor(sequelize, DataTypes) {
  const Motorcycle = sequelize.define('Motorcycle', {
    brand: DataTypes.STRING,
    model: DataTypes.STRING,
    year: DataTypes.STRING,
    category: DataTypes.STRING,
    cc: DataTypes.STRING,
    cylinders_numbers: DataTypes.STRING,
    engine_type: DataTypes.STRING,
    power: DataTypes.STRING,
    torque: DataTypes.STRING,
    compression: DataTypes.STRING,
    bore: DataTypes.STRING,
    stroke: DataTypes.STRING,
    fuel_system: DataTypes.STRING,
    fuel_control: DataTypes.STRING,
    ignition: DataTypes.STRING,
    lubrification: DataTypes.STRING,
    cooling: DataTypes.STRING,
    gearbox: DataTypes.STRING,
    transmission: DataTypes.STRING,
    clutch: DataTypes.STRING,
    frame_type: DataTypes.STRING,
    front_suspension: DataTypes.STRING,
    front_wheel_travel: DataTypes.STRING,
    rear_suspension: DataTypes.STRING,
    rear_wheel_travel: DataTypes.STRING,
    front_tyre: DataTypes.STRING,
    rear_tyre: DataTypes.STRING,
    front_brakes: DataTypes.STRING,
    front_brakes_diameter: DataTypes.STRING,
    rear_brakes: DataTypes.STRING,
    rear_brakes_diameter: DataTypes.STRING,
    dry_weight: DataTypes.STRING,
    power_weight_ratio: DataTypes.STRING,
    seat_height: DataTypes.STRING,
    overall_height: DataTypes.STRING,
    overall_length: DataTypes.STRING,
    overall_width: DataTypes.STRING,
    ground_clearance: DataTypes.STRING,
    wheelbase: DataTypes.STRING,
    fuel_capacity: DataTypes.STRING,
    starter: DataTypes.STRING,
    _source: DataTypes.STRING,
  });

  return Motorcycle;
};
